version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing dependencies"
      - apt-get update && apt-get install -y maven
  build:
    commands:
      - echo "Building the project"
      - mvn clean install
artifacts:
  files:
    - target/*.jar

